# streamlit_app.py
# ---
# "Beta Hunt" – Streamlit classroom app
# Students submit three stocks: beta ≈ 0, beta ≈ 1, and highest beta they can find.
# They enter the three betas and upload proof screenshots. A real-time leaderboard ranks results.
#
# Backend: Supabase (Postgres + Storage). Configure via Streamlit Secrets (see below).
# This version avoids deprecated/fragile patterns and has clear error messages for common setup issues.
#
# ------------------------------
# STREAMLIT SECRETS (required)
# In your app settings → Secrets:
# [supabase]
# url = "https://YOUR_PROJECT_ID.supabase.co"
# key = "YOUR_ANON_KEY"
# bucket = "screenshots"
# table = "submissions"
# admin_passphrase = "changeme"
#
# Supabase SQL (run once in SQL editor):
# CREATE TABLE IF NOT EXISTS public.submissions (
#   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
#   team TEXT NOT NULL,
#   student_name TEXT,
#   email TEXT,
#   section TEXT,
#   stock0 TEXT,      beta0 DOUBLE PRECISION,
#   stock1 TEXT,      beta1 DOUBLE PRECISION,
#   stock_hi TEXT,    beta_hi DOUBLE PRECISION,
#   shot0_url TEXT, shot1_url TEXT, shothi_url TEXT,
#   notes TEXT
# );
#
# If your table already exists, add the section column:
# ALTER TABLE public.submissions ADD COLUMN IF NOT EXISTS section TEXT;
# ------------------------------

from __future__ import annotations
import time
import uuid
from datetime import datetime, timezone
from typing import Dict, Any, List
from io import BytesIO

import streamlit as st

try:
    from supabase import create_client, Client
except Exception as e:
    st.error("Supabase client not installed. Add `supabase` (or `supabase-py`) to requirements.txt and reboot the app.")
    st.stop()

try:
    import pandas as pd
except Exception as e:
    st.error("Pandas not installed. Add `pandas` to requirements.txt and reboot the app.")
    st.stop()

try:
    from PIL import Image, ImageDraw, ImageFont
except Exception as e:
    st.error("Pillow not installed. Add `pillow` to requirements.txt and reboot the app.")
    st.stop()

TARGETS = {"near_zero": 0.0, "near_one": 1.0}
BETA_MIN, BETA_MAX = -5.0, 20.0
APP_TITLE = "📈 Beta Hunt: Find 0, 1, and Highest"

# ---------- Helpers ----------
@st.cache_resource(show_spinner=False)
def get_client() -> Client:
    cfg = st.secrets.get("supabase", {})
    url = cfg.get("url")
    key = cfg.get("key")
    if not url or not key:
        st.error("Missing Supabase credentials in Secrets. Please set [supabase].url and .key.")
        st.stop()
    return create_client(url, key)


def check_database_health():
    """Check if Supabase is accessible and not paused."""
    try:
        sb = get_client()
        _, table, _ = get_storage_cfg()
        sb.table(table).select("id").limit(1).execute()
        return True
    except Exception as e:
        error_msg = str(e).lower()
        if "connection" in error_msg or "timeout" in error_msg or "fetch" in error_msg or "api" in error_msg:
            st.error("🛑 **Supabase Database is Paused or Unavailable**")
            st.warning("""
            Your Supabase project appears to be paused (inactive for 7+ days) or unreachable.
            
            **To restore it:**
            1. Go to [supabase.com/dashboard](https://supabase.com/dashboard)
            2. Find your project
            3. Click the **"Restore"** or **"Resume"** button
            4. Wait 10-30 seconds for it to wake up
            5. Refresh this page
            
            Your data is safe and will be restored!
            """)
            st.stop()
        else:
            st.error(f"❌ Database connection error: {e}")
            st.stop()
        return False


@st.cache_resource(show_spinner=False)
def get_storage_cfg():
    cfg = st.secrets.get("supabase", {})
    bucket = cfg.get("bucket", "screenshots")
    table = cfg.get("table", "submissions")
    admin_pw = cfg.get("admin_passphrase", "")
    return bucket, table, admin_pw


def _safe_float(x):
    try:
        return float(x)
    except Exception:
        return None


def validate_email(email: str) -> bool:
    """Check if email has valid format."""
    if not email or not email.strip():
        return False
    email = email.strip()
    # Basic validation: must have @ and a dot after it
    if '@' not in email:
        return False
    parts = email.split('@')
    if len(parts) != 2:
        return False
    local, domain = parts
    if not local or not domain:
        return False
    if '.' not in domain:
        return False
    return True


def validate_betas(beta0, beta1, betahi) -> List[str]:
    errs = []
    for label, val in [("beta near 0", beta0), ("beta near 1", beta1), ("highest beta", betahi)]:
        if val is None:
            errs.append(f"Please enter a numeric value for {label}.")
        elif val < BETA_MIN or val > BETA_MAX:
            errs.append(f"{label} looks out of range (must be between {BETA_MIN:g} and {BETA_MAX:g}).")
    return errs


def validate_file_uploads(shot0, shot1, shothi) -> List[str]:
    """Validate uploaded files for size and type."""
    max_size_mb = 5  # 5MB limit per file
    max_size_bytes = max_size_mb * 1024 * 1024
    
    errors = []
    for label, file in [("Near 0 screenshot", shot0), ("Near 1 screenshot", shot1), ("Highest beta screenshot", shothi)]:
        if file:
            file_size = getattr(file, "size", 0)
            if file_size > max_size_bytes:
                errors.append(f"{label} is too large ({file_size / 1024 / 1024:.1f}MB). Maximum size is {max_size_mb}MB.")
            if file_size == 0:
                errors.append(f"{label} appears to be empty.")
    
    return errors


def upload_to_storage(sb: Client, file, path: str, bucket: str) -> str:
    """Upload the file-like to Supabase Storage and return a public URL.
    Keeps the correct extension for PNG/JPG/PDF and uses upsert for resubmits.
    """
    if not file or getattr(file, "size", 0) == 0:
        return ""

    # Infer extension from MIME
    mime = (getattr(file, "type", None) or "").lower()
    ext = ".bin"
    if "png" in mime:
        ext = ".png"
    elif "jpeg" in mime or mime.endswith("/jpg"):
        ext = ".jpg"
    elif "pdf" in mime:
        ext = ".pdf"
    if not path.endswith(ext):
        path = path + ext

    data = file.read()
    if hasattr(file, "seek"):
        file.seek(0)

    try:
        # supabase-py v2 signature supports bytes and file_options
        sb.storage.from_(bucket).upload(
            path=path,
            file=data,
            file_options={"content-type": mime or "application/octet-stream", "x-upsert": "true"},
        )
        return sb.storage.from_(bucket).get_public_url(path)
    except Exception as e:
        # Provide helpful error message
        error_msg = str(e).lower()
        if "not found" in error_msg:
            st.error(f"❌ Storage bucket '{bucket}' doesn't exist. Please create it in Supabase Dashboard → Storage.")
        elif "permission" in error_msg or "unauthorized" in error_msg:
            st.error(f"❌ Permission denied. Make sure your bucket '{bucket}' has RLS policies allowing uploads.")
        elif "timeout" in error_msg or "connection" in error_msg or "network" in error_msg:
            st.error(f"❌ Upload failed due to connection timeout. This usually means the file is too large or your connection is unstable.")
            st.info("💡 Try:\n- Using a smaller file (compress or crop your screenshot)\n- Checking your internet connection\n- Trying again in a few moments")
        elif "payload too large" in error_msg or "413" in error_msg:
            st.error(f"❌ File is too large for upload. Maximum file size is 5MB.")
            st.info("💡 Please compress or crop your screenshot to make it smaller.")
        else:
            st.error(f"❌ Upload failed: {error_msg}")
            st.info("If this persists, please contact your instructor.")
        st.stop()


def save_submission(team: str, student_name: str, email: str, section: str, row: Dict[str, Any], files: Dict[str, Any]):
    sb = get_client()
    bucket, table, _ = get_storage_cfg()

    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    # Unique file keys per upload
    shot0_url = upload_to_storage(sb, files.get("shot0"), f"{team}/{ts}-near0-{uuid.uuid4().hex}", bucket) if files.get("shot0") else ""
    shot1_url = upload_to_storage(sb, files.get("shot1"), f"{team}/{ts}-near1-{uuid.uuid4().hex}", bucket) if files.get("shot1") else ""
    shothi_url = upload_to_storage(sb, files.get("shothi"), f"{team}/{ts}-high-{uuid.uuid4().hex}", bucket) if files.get("shothi") else ""

    payload = {
        "team": (team or "").strip(),
        "student_name": (student_name or "").strip(),
        "email": (email or "").strip(),
        "section": (section or "").strip(),
        "stock0": (row.get("stock0") or "").strip().upper(),
        "beta0": row.get("beta0"),
        "stock1": (row.get("stock1") or "").strip().upper(),
        "beta1": row.get("beta1"),
        "stock_hi": (row.get("stock_hi") or "").strip().upper(),
        "beta_hi": row.get("beta_hi"),
        "shot0_url": shot0_url,
        "shot1_url": shot1_url,
        "shothi_url": shothi_url,
        "notes": (row.get("notes") or "").strip(),
    }

    try:
        res = sb.table(table).insert(payload).execute()
        return {"res": res, "shot0_url": shot0_url, "shot1_url": shot1_url, "shothi_url": shothi_url}
    except Exception as e:
        error_msg = str(e)
        st.error(f"❌ Database error: {error_msg}")
        st.error("This is likely a Row Level Security (RLS) policy issue. Please check the setup instructions below.")
        st.stop()


def fetch_latest_by_team() -> List[Dict[str, Any]]:
    sb = get_client()
    _, table, _ = get_storage_cfg()
    res = sb.table(table).select("*").order("created_at", desc=True).execute()
    rows = res.data or []

    # Keep only the most recent per team
    latest = {}
    for r in rows:
        t = (r.get("team") or "").strip()
        if t and t not in latest:
            latest[t] = r
    return list(latest.values())


def fetch_latest_by_section(section: str) -> List[Dict[str, Any]]:
    """Fetch latest submissions filtered by section."""
    sb = get_client()
    _, table, _ = get_storage_cfg()
    res = sb.table(table).select("*").eq("section", section).order("created_at", desc=True).execute()
    rows = res.data or []

    # Keep only the most recent per team within this section
    latest = {}
    for r in rows:
        t = (r.get("team") or "").strip()
        if t and t not in latest:
            latest[t] = r
    return list(latest.values())


def fetch_all_submissions() -> List[Dict[str, Any]]:
    """Fetch all submissions (not just latest per team) for export."""
    sb = get_client()
    _, table, _ = get_storage_cfg()
    res = sb.table(table).select("*").order("created_at", desc=True).execute()
    return res.data or []


def export_to_excel(rows: List[Dict[str, Any]]) -> BytesIO:
    """Convert submissions to Excel format with clickable hyperlinks."""
    # Select relevant columns for export
    data = []
    for r in rows:
        data.append({
            "Submitted": r.get("created_at"),
            "Name": r.get("student_name"),
            "Email": r.get("email"),
            "Section": r.get("section"),
            "Stock (Near 0)": r.get("stock0"),
            "Beta (Near 0)": r.get("beta0"),
            "Screenshot URL (Near 0)": r.get("shot0_url"),
            "Stock (Near 1)": r.get("stock1"),
            "Beta (Near 1)": r.get("beta1"),
            "Screenshot URL (Near 1)": r.get("shot1_url"),
            "Stock (Highest)": r.get("stock_hi"),
            "Beta (Highest)": r.get("beta_hi"),
            "Screenshot URL (Highest)": r.get("shothi_url"),
            "Notes": r.get("notes"),
        })
    
    df = pd.DataFrame(data)
    
    # Create Excel file in memory
    output = BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='Submissions')
        
        # Get the worksheet to add hyperlinks
        worksheet = writer.sheets['Submissions']
        
        # Find URL columns (columns G, J, M - adjusted for new Section column)
        url_columns = {
            'G': 'Screenshot URL (Near 0)',
            'J': 'Screenshot URL (Near 1)', 
            'M': 'Screenshot URL (Highest)'
        }
        
        # Convert URLs to hyperlinks (start from row 2, skip header)
        for row_idx in range(2, len(df) + 2):  # Excel rows are 1-based, +1 for header
            for col_letter, col_name in url_columns.items():
                cell = worksheet[f'{col_letter}{row_idx}']
                url = cell.value
                if url and isinstance(url, str) and url.startswith('http'):
                    # Create hyperlink
                    cell.hyperlink = url
                    cell.value = "View Screenshot"
                    cell.style = "Hyperlink"
    
    output.seek(0)
    return output


def export_top3_leaderboard(section: str) -> BytesIO:
    """Export top 3 for each category as an image using PIL."""
    rows = fetch_latest_by_section(section)
    scores = compute_scores(rows)
    
    # Image settings
    width = 1600
    height = 700
    bg_color = (255, 255, 255)
    brand_color = (9, 155, 221)
    header_bg = brand_color
    header_text = (255, 255, 255)
    alt_row_bg = (245, 245, 245)
    border_color = (200, 200, 200)
    
    # Create image
    img = Image.new('RGB', (width, height), bg_color)
    draw = ImageDraw.Draw(img)
    
    # Try to use a nice font, fall back to default if not available
    try:
        title_font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 32)
        header_font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 18)
        cell_font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 14)
    except:
        title_font = ImageFont.load_default()
        header_font = ImageFont.load_default()
        cell_font = ImageFont.load_default()
    
    # Draw main title
    title_text = f"{section} - Beta Hunt Leaderboard"
    title_bbox = draw.textbbox((0, 0), title_text, font=title_font)
    title_width = title_bbox[2] - title_bbox[0]
    draw.text(((width - title_width) // 2, 15), title_text, fill=brand_color, font=title_font)
    
    # Helper function to draw a table
    def draw_table(x, y, title, headers, data, col_widths):
        current_y = y
        
        # Draw table title
        title_bbox = draw.textbbox((0, 0), title, font=header_font)
        title_w = title_bbox[2] - title_bbox[0]
        draw.text((x + (sum(col_widths) - title_w) // 2, current_y), title, fill=(0, 0, 0), font=header_font)
        current_y += 28
        
        # Draw header row
        current_x = x
        row_height = 30
        for i, (header, col_w) in enumerate(zip(headers, col_widths)):
            # Header background
            draw.rectangle([current_x, current_y, current_x + col_w, current_y + row_height], 
                          fill=header_bg, outline=border_color)
            # Header text
            text_bbox = draw.textbbox((0, 0), header, font=header_font)
            text_w = text_bbox[2] - text_bbox[0]
            text_h = text_bbox[3] - text_bbox[1]
            draw.text((current_x + (col_w - text_w) // 2, current_y + (row_height - text_h) // 2), 
                     header, fill=header_text, font=header_font)
            current_x += col_w
        
        current_y += row_height
        
        # Draw data rows
        for row_idx, row_data in enumerate(data):
            current_x = x
            bg = alt_row_bg if row_idx % 2 == 1 else bg_color
            
            for col_idx, (cell_text, col_w) in enumerate(zip(row_data, col_widths)):
                # Cell background
                draw.rectangle([current_x, current_y, current_x + col_w, current_y + row_height], 
                              fill=bg, outline=border_color)
                # Cell text
                cell_str = str(cell_text)
                text_bbox = draw.textbbox((0, 0), cell_str, font=cell_font)
                text_w = text_bbox[2] - text_bbox[0]
                text_h = text_bbox[3] - text_bbox[1]
                draw.text((current_x + (col_w - text_w) // 2, current_y + (row_height - text_h) // 2), 
                         cell_str, fill=(0, 0, 0), font=cell_font)
                current_x += col_w
            
            current_y += row_height
    
    # Table 1: Closest to 0 (top left)
    table1_data = []
    for i, r in enumerate(scores["near0"][:3]):
        table1_data.append([
            i+1,
            r.get('student_name', 'N/A'),
            r.get('stock0', 'N/A'),
            f"{r.get('beta0', 0):.4f}",
            f"{r.get('err0', 0):.4f}"
        ])
    draw_table(50, 70, "Closest to Beta = 0", 
              ["Rank", "Name", "Stock", "Beta", "Error"],
              table1_data, [60, 200, 100, 100, 100])
    
    # Table 2: Closest to 1 (top right)
    table2_data = []
    for i, r in enumerate(scores["near1"][:3]):
        table2_data.append([
            i+1,
            r.get('student_name', 'N/A'),
            r.get('stock1', 'N/A'),
            f"{r.get('beta1', 0):.4f}",
            f"{r.get('err1', 0):.4f}"
        ])
    draw_table(840, 70, "Closest to Beta = 1",
              ["Rank", "Name", "Stock", "Beta", "Error"],
              table2_data, [60, 200, 100, 100, 100])
    
    # Table 3: Highest Beta (bottom left) - minimal spacing
    table3_data = []
    for i, r in enumerate(scores["high"][:3]):
        table3_data.append([
            i+1,
            r.get('student_name', 'N/A'),
            r.get('stock_hi', 'N/A'),
            f"{r.get('beta_hi', 0):.4f}"
        ])
    draw_table(50, 310, "Highest Beta",
              ["Rank", "Name", "Stock", "Beta"],
              table3_data, [60, 240, 120, 100])
    
    # Table 4: Overall (bottom right) - minimal spacing
    table4_data = []
    for i, r in enumerate(scores["overall"][:3]):
        table4_data.append([
            i+1,
            r.get('student_name', 'N/A'),
            r.get('rank0', '-'),
            r.get('rank1', '-'),
            r.get('rankh', '-'),
            r.get('total_rank', 0)
        ])
    draw_table(840, 310, "Overall (Sum of Ranks)",
              ["Rank", "Name", "Near 0", "Near 1", "High Beta", "Total"],
              table4_data, [60, 180, 80, 80, 80, 80])
    
    # Save to BytesIO
    output = BytesIO()
    img.save(output, format='PNG')
    output.seek(0)
    return output


def compute_scores(rows: List[Dict[str, Any]]):
    for r in rows:
        r["err0"] = None if r.get("beta0") is None else abs(r["beta0"] - TARGETS["near_zero"])
        r["err1"] = None if r.get("beta1") is None else abs(r["beta1"] - TARGETS["near_one"])
        r["hi_score"] = None if r.get("beta_hi") is None else r["beta_hi"]

    near0 = [r for r in rows if r.get("err0") is not None]
    near1 = [r for r in rows if r.get("err1") is not None]
    high  = [r for r in rows if r.get("hi_score") is not None]

    near0.sort(key=lambda r: r["err0"])                # closer to 0 is better
    near1.sort(key=lambda r: r["err1"])                # closer to 1 is better
    high.sort(key=lambda r: r["hi_score"], reverse=True)  # higher is better

    rank0 = {r["team"]: i+1 for i, r in enumerate(near0)}
    rank1 = {r["team"]: i+1 for i, r in enumerate(near1)}
    rankh = {r["team"]: i+1 for i, r in enumerate(high)}

    for r in rows:
        r["rank0"] = rank0.get(r.get("team"))
        r["rank1"] = rank1.get(r.get("team"))
        r["rankh"] = rankh.get(r.get("team"))
        ranks = [x for x in (r["rank0"], r["rank1"], r["rankh"]) if x is not None]
        r["total_rank"] = sum(ranks) if ranks else None

    overall = [r for r in rows if r.get("total_rank") is not None]
    overall.sort(key=lambda r: (r["total_rank"], r.get("created_at")))

    return {"near0": near0, "near1": near1, "high": high, "overall": overall}

# ---------- UI ----------
st.set_page_config(page_title="Beta Hunt – Leaderboard", page_icon="📈", layout="wide")
st.title(APP_TITLE)

st.caption("Submit three stocks with betas and screenshots as proof. Each student can submit only once.")

# Check database health on app load
check_database_health()

# Branding (optional): light accent line using your brand color (RGB 9,155,221)
st.markdown("""
<style>
:root { --brand: rgb(9,155,221); }
.block-container { padding-top: 2rem; }
h1, h2, h3 { font-family: Calibri, Arial, sans-serif; }
hr { border: none; height: 2px; background: linear-gradient(90deg, var(--brand), transparent); }
</style>
""", unsafe_allow_html=True)

submit_tab, leaderboard_tab, admin_tab = st.tabs(["Submit", "Leaderboard", "Admin 🔒"])

with submit_tab:
    st.subheader("Submit your picks")
    with st.form("submission_form", clear_on_submit=False):
        student_name = st.text_input("Your name *")
        email = st.text_input("Email *")
        section = st.selectbox("Section *", options=["-- Select your section --", "Section F1", "Section F2"])

        st.markdown("---")
        st.markdown("**1) Near 0 beta**")
        c1, c2, c3 = st.columns([2,1,2])
        with c1:
            stock0 = st.text_input("Ticker / Company", key="stock0")
        with c2:
            beta0 = st.text_input("Beta", key="beta0")
        with c3:
            shot0 = st.file_uploader("Screenshot (PNG/JPG/PDF) *", type=["png","jpg","jpeg","pdf"], key="shot0")

        st.markdown("**2) Near 1 beta**")
        c1, c2, c3 = st.columns([2,1,2])
        with c1:
            stock1 = st.text_input("Ticker / Company", key="stock1")
        with c2:
            beta1 = st.text_input("Beta", key="beta1")
        with c3:
            shot1 = st.file_uploader("Screenshot (PNG/JPG/PDF) *", type=["png","jpg","jpeg","pdf"], key="shot1")

        st.markdown("**3) Highest beta**")
        c1, c2, c3 = st.columns([2,1,2])
        with c1:
            stock_hi = st.text_input("Ticker / Company", key="stock_hi")
        with c2:
            beta_hi = st.text_input("Beta", key="beta_hi")
        with c3:
            shothi = st.file_uploader("Screenshot (PNG/JPG/PDF) *", type=["png","jpg","jpeg","pdf"], key="shothi")

        notes = st.text_area("Notes (optional)")
        agree = st.checkbox("I confirm these values are taken from a reliable source and the screenshots are unedited.")
        submitted = st.form_submit_button("Submit my entry", use_container_width=True)

    if submitted:
        # Required fields
        if not student_name or not student_name.strip():
            st.error("Please enter your name.")
            st.stop()
        if not email or not email.strip():
            st.error("Please enter your email.")
            st.stop()
        if not validate_email(email):
            st.error("Please enter a valid email address (e.g., student@university.edu).")
            st.stop()
        if not section or section == "-- Select your section --":
            st.error("Please select your section (F1 or F2).")
            st.stop()
        
        # Check if this email has already submitted
        sb = get_client()
        _, table_name, _ = get_storage_cfg()
        try:
            existing = sb.table(table_name).select("id").eq("team", email.strip().lower()).execute()
            if existing.data and len(existing.data) > 0:
                st.error("❌ This email has already submitted. Each student can only submit once. If you need to change your submission, please contact the instructor.")
                st.stop()
        except Exception as e:
            st.error("❌ Database error while checking existing submissions. The database might be paused.")
            st.info("Please refresh the page. If the error persists, the instructor needs to restore the Supabase database.")
            st.stop()
        
        # Check screenshots are uploaded
        if not shot0:
            st.error("Please upload a screenshot for the near 0 beta stock.")
            st.stop()
        if not shot1:
            st.error("Please upload a screenshot for the near 1 beta stock.")
            st.stop()
        if not shothi:
            st.error("Please upload a screenshot for the highest beta stock.")
            st.stop()
        
        # Validate file sizes
        file_errors = validate_file_uploads(shot0, shot1, shothi)
        if file_errors:
            for err in file_errors:
                st.error(err)
            st.info("💡 **Tip:** If your screenshots are too large, try:\n- Taking a new screenshot at lower resolution\n- Compressing the image using a free tool like TinyPNG\n- Converting PNG to JPG (usually smaller)\n- Cropping to show only the relevant beta information")
            st.stop()
        
        b0 = _safe_float(beta0)
        b1 = _safe_float(beta1)
        bhi = _safe_float(beta_hi)
        errs = validate_betas(b0, b1, bhi)
        if not agree:
            errs.append("Please tick the confirmation checkbox.")
        if errs:
            for e in errs:
                st.error(e)
            st.stop()
        with st.spinner("Saving your submission..."):
            result = save_submission(
                team=(email or "").strip().lower(),
                student_name=student_name,
                email=email,
                section=section,
                row={
                    "stock0": stock0,
                    "beta0": b0,
                    "stock1": stock1,
                    "beta1": b1,
                    "stock_hi": stock_hi,
                    "beta_hi": bhi,
                    "notes": notes,
                },
                files={"shot0": shot0, "shot1": shot1, "shothi": shothi},
            )
        # Show upload links if available
        urls = [
            ("Near 0", result.get("shot0_url")),
            ("Near 1", result.get("shot1_url")),
            ("Highest", result.get("shothi_url")),
        ]
        have_any = any(u for _, u in urls)
        if have_any:
            st.toast("Uploads saved", icon="✅")
            upload_text = "**Evidence uploaded:**\n" + "\n".join([f"- {label}: [{url}]({url})" for label, url in urls if url])
            st.markdown(upload_text)
        st.success("Submitted ✓")
        time.sleep(3)  # Display success message for 3 seconds
        try:
            st.rerun()                 # Streamlit ≥ 1.32
        except Exception:
            st.experimental_rerun()    # fallback

with leaderboard_tab:
    st.subheader("Live leaderboard")

    # Manual refresh button (robust & version-safe)
    if st.button("🔄 Refresh leaderboard"):
        try:
            st.rerun()
        except Exception:
            st.experimental_rerun()

    # Create tabs for each section
    f1_tab, f2_tab = st.tabs(["Section F1", "Section F2"])
    
    with f1_tab:
        st.markdown("#### Section F1 Rankings")
        rows_f1 = fetch_latest_by_section("Section F1")
        scores_f1 = compute_scores(rows_f1)
        
        c1, c2, c3 = st.columns(3)
        with c1:
            st.markdown("### 🥇 Closest to 0")
            data = [{
                "Rank": i+1,
                "Name": r.get("student_name"),
                "Stock": r.get("stock0"),
                "Beta": r.get("beta0"),
                "Error": round(r.get("err0"), 4) if r.get("err0") is not None else None,
                "Submitted": r.get("created_at", "")[:16].replace("T", " ") if r.get("created_at") else "",
            } for i, r in enumerate(scores_f1["near0"][:10])]
            st.dataframe(data, use_container_width=True, hide_index=True)

        with c2:
            st.markdown("### 🥈 Closest to 1")
            data = [{
                "Rank": i+1,
                "Name": r.get("student_name"),
                "Stock": r.get("stock1"),
                "Beta": r.get("beta1"),
                "Error": round(r.get("err1"), 4) if r.get("err1") is not None else None,
                "Submitted": r.get("created_at", "")[:16].replace("T", " ") if r.get("created_at") else "",
            } for i, r in enumerate(scores_f1["near1"][:10])]
            st.dataframe(data, use_container_width=True, hide_index=True)

        with c3:
            st.markdown("### 🥉 Highest beta")
            data = [{
                "Rank": i+1,
                "Name": r.get("student_name"),
                "Stock": r.get("stock_hi"),
                "Beta": r.get("beta_hi"),
                "Submitted": r.get("created_at", "")[:16].replace("T", " ") if r.get("created_at") else "",
            } for i, r in enumerate(scores_f1["high"][:10])]
            st.dataframe(data, use_container_width=True, hide_index=True)

        st.markdown("---")
        st.markdown("### Overall (sum of ranks)")
        data = [{
            "Rank": i+1,
            "Name": r.get("student_name"),
            "Near 0 rank": r.get("rank0"),
            "Near 1 rank": r.get("rank1"),
            "High beta rank": r.get("rankh"),
            "Total": r.get("total_rank"),
            "Submitted": r.get("created_at", "")[:16].replace("T", " ") if r.get("created_at") else "",
        } for i, r in enumerate(scores_f1["overall"][:20])]
        st.dataframe(data, use_container_width=True, hide_index=True)
    
    with f2_tab:
        st.markdown("#### Section F2 Rankings")
        rows_f2 = fetch_latest_by_section("Section F2")
        scores_f2 = compute_scores(rows_f2)
        
        c1, c2, c3 = st.columns(3)
        with c1:
            st.markdown("### 🥇 Closest to 0")
            data = [{
                "Rank": i+1,
                "Name": r.get("student_name"),
                "Stock": r.get("stock0"),
                "Beta": r.get("beta0"),
                "Error": round(r.get("err0"), 4) if r.get("err0") is not None else None,
                "Submitted": r.get("created_at", "")[:16].replace("T", " ") if r.get("created_at") else "",
            } for i, r in enumerate(scores_f2["near0"][:10])]
            st.dataframe(data, use_container_width=True, hide_index=True)

        with c2:
            st.markdown("### 🥈 Closest to 1")
            data = [{
                "Rank": i+1,
                "Name": r.get("student_name"),
                "Stock": r.get("stock1"),
                "Beta": r.get("beta1"),
                "Error": round(r.get("err1"), 4) if r.get("err1") is not None else None,
                "Submitted": r.get("created_at", "")[:16].replace("T", " ") if r.get("created_at") else "",
            } for i, r in enumerate(scores_f2["near1"][:10])]
            st.dataframe(data, use_container_width=True, hide_index=True)

        with c3:
            st.markdown("### 🥉 Highest beta")
            data = [{
                "Rank": i+1,
                "Name": r.get("student_name"),
                "Stock": r.get("stock_hi"),
                "Beta": r.get("beta_hi"),
                "Submitted": r.get("created_at", "")[:16].replace("T", " ") if r.get("created_at") else "",
            } for i, r in enumerate(scores_f2["high"][:10])]
            st.dataframe(data, use_container_width=True, hide_index=True)

        st.markdown("---")
        st.markdown("### Overall (sum of ranks)")
        data = [{
            "Rank": i+1,
            "Name": r.get("student_name"),
            "Near 0 rank": r.get("rank0"),
            "Near 1 rank": r.get("rank1"),
            "High beta rank": r.get("rankh"),
            "Total": r.get("total_rank"),
            "Submitted": r.get("created_at", "")[:16].replace("T", " ") if r.get("created_at") else "",
        } for i, r in enumerate(scores_f2["overall"][:20])]
        st.dataframe(data, use_container_width=True, hide_index=True)

with admin_tab:
    st.subheader("Admin tools")
    _, table_name, admin_pw = get_storage_cfg()
    entered = st.text_input("Admin passphrase", type="password")
    
    if entered and entered == admin_pw:
        st.success("Access granted")
        sb = get_client()
        
        st.markdown("### Export submissions")
        if st.button("📥 Download all submissions as Excel"):
            with st.spinner("Preparing Excel file..."):
                all_submissions = fetch_all_submissions()
                if all_submissions:
                    excel_file = export_to_excel(all_submissions)
                    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                    st.download_button(
                        label="💾 Download Excel File",
                        data=excel_file,
                        file_name=f"beta_hunt_submissions_{timestamp}.xlsx",
                        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    )
                    st.success(f"✅ Ready! Found {len(all_submissions)} submission(s).")
                else:
                    st.info("No submissions to export yet.")
        
        st.markdown("### Export Top 3 Leaderboards (for forums)")
        st.caption("Download images showing top 3 in each category, perfect for posting to discussion forums.")
        
        col1, col2 = st.columns(2)
        with col1:
            if st.button("📋 Generate F1 Top 3 Image"):
                with st.spinner("Creating image..."):
                    top3_image = export_top3_leaderboard("Section F1")
                    st.download_button(
                        label="💾 Download F1 Leaderboard Image",
                        data=top3_image,
                        file_name="beta_hunt_top3_F1.png",
                        mime="image/png",
                    )
        
        with col2:
            if st.button("📋 Generate F2 Top 3 Image"):
                with st.spinner("Creating image..."):
                    top3_image = export_top3_leaderboard("Section F2")
                    st.download_button(
                        label="💾 Download F2 Leaderboard Image",
                        data=top3_image,
                        file_name="beta_hunt_top3_F2.png",
                        mime="image/png",
                    )
        
        st.markdown("---")
        st.markdown("### Delete specific submissions")
        team_to_delete = st.text_input("Email to delete")
        if st.button("Delete submissions") and team_to_delete.strip():
            sb.table(table_name).delete().eq("team", team_to_delete.strip()).execute()
            st.success(f"Deleted submissions for '{team_to_delete}'.")
        
        st.markdown("---")
        st.markdown("### Delete all submissions")
        st.warning("⚠️ This will permanently delete ALL submissions from the database!")
        confirm_delete_all = st.checkbox("I understand this will delete everything")
        if st.button("Delete ALL submissions", type="primary") and confirm_delete_all:
            # Delete all rows from the table
            sb.table(table_name).delete().neq("id", 0).execute()  # neq with impossible condition deletes all
            st.success("All submissions have been deleted.")
            time.sleep(1)
            try:
                st.rerun()
            except Exception:
                st.experimental_rerun()
    else:
        st.info("Enter the admin passphrase to access exports and deletion tools.")
